
import React, { useState } from 'react';
import pptxgen from "pptxgenjs";
import { generatePresentation } from '../src/services/geminiService';
import { PresentationSlide, Topic } from '../src/types';
import { RefreshCw, FileDown, CheckCircle, Presentation, Layout } from 'lucide-react';

interface PresentationGeneratorProps {
  topic: Topic;
  subject: string;
  level: string;
  generatedImage: string | null;
  onSave: (data: PresentationSlide[]) => void;
}

export const PresentationGenerator: React.FC<PresentationGeneratorProps> = ({ 
  topic, subject, level, generatedImage, onSave 
}) => {
  const [slideCount, setSlideCount] = useState(10);
  const [tone, setTone] = useState("Professional");
  const [isGenerating, setIsGenerating] = useState(false);
  const [slides, setSlides] = useState<PresentationSlide[] | null>(null);

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const data = await generatePresentation(topic, subject, level, slideCount, tone);
      setSlides(data);
      onSave(data);
    } catch (e) {
      console.error(e);
      alert("Failed to generate presentation. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = async () => {
    if (!slides) return;

    const pres = new pptxgen();
    
    // Metadata
    pres.title = topic.title;
    pres.subject = subject;
    pres.author = "InfographAI";
    pres.layout = "LAYOUT_16x9";

    // --- DESIGN THEME ---
    // We define a Master Slide for consistent, high-quality branding
    
    // 1. Title Master
    pres.defineSlideMaster({
      title: "TITLE_SLIDE",
      background: { color: "FFFFFF" },
      objects: [
        // Decorative Sidebar/Shape
        { rect: { x: 0, y: 0, w: 0.5, h: "100%", fill: { color: "4F46E5" } } }, // Indigo Bar
        { rect: { x: 0.5, y: 0, w: "100%", h: 1.5, fill: { color: "F1F5F9" } } }, // Light header background
        // Logo/Brand text
        { text: { text: "INFOGRAPH.AI", options: { x: 0.7, y: 0.4, fontSize: 14, color: "94A3B8", bold: true, charSpacing: 10 } } },
      ]
    });

    // 2. Content Master
    pres.defineSlideMaster({
      title: "CONTENT_SLIDE",
      background: { color: "FFFFFF" },
      objects: [
        // Header Bar
        { rect: { x: 0, y: 0, w: "100%", h: 1.2, fill: { color: "1E293B" } } }, // Slate-900 Header
        // Accent Line
        { rect: { x: 0, y: 1.2, w: "100%", h: 0.05, fill: { color: "4F46E5" } } },
        // Footer Line
        { line: { x: 0.5, y: 7.0, w: 9.0, h: 0, line: { color: "E2E8F0", width: 1 } } },
        // Brand Footer
        { text: { text: `Generated by InfographAI • ${subject}`, options: { x: 0.5, y: 7.1, w: 5, h: 0.3, fontSize: 10, color: "94A3B8" } } }
      ],
      slideNumber: { x: 9.0, y: 7.1, fontSize: 10, color: "94A3B8" }
    });

    // --- GENERATE SLIDES ---

    slides.forEach((slide, index) => {
      // Choose Master based on slide type
      const isTitle = slide.type === 'title';
      const masterName = isTitle ? "TITLE_SLIDE" : "CONTENT_SLIDE";
      
      const s = pres.addSlide({ masterName });

      // Add Speaker Notes
      if (slide.speakerNotes) {
        s.addNotes(slide.speakerNotes);
      }

      if (isTitle) {
        // --- TITLE SLIDE LAYOUT ---
        
        // Main Title
        s.addText(slide.title, { 
            x: 1.0, y: 2.0, w: 8.0, h: 1.5, 
            fontSize: 44, fontFace: "Helvetica Neue", 
            color: "1E293B", bold: true, align: "left", valign: "top" 
        });
        
        // Subtitle / Context
        s.addText(`${subject.toUpperCase()}  |  ${level.toUpperCase()}`, {
            x: 1.0, y: 1.5, w: 8.0, h: 0.5,
            fontSize: 12, color: "4F46E5", bold: true, charSpacing: 15
        });

        // Infographic Image (if available) - placed nicely on the right or bottom
        if (generatedImage) {
            // Add a subtle shadow/border effect using a rect behind the image
            s.addShape(pres.ShapeType.rect, { 
                x: 5.5, y: 1.5, w: 4.0, h: 4.0, 
                fill: { color: "F8FAFC" }, line: { color: "E2E8F0", width: 1 } 
            });
            
            s.addImage({ 
                data: generatedImage, 
                x: 5.75, y: 1.75, w: 3.5, h: 3.5, 
                sizing: { type: "contain", w: 3.5, h: 3.5 } 
            });
        }

      } else {
        // --- CONTENT SLIDE LAYOUT ---

        // Slide Title (in the dark header area)
        s.addText(slide.title, { 
            x: 0.5, y: 0.3, w: 9, h: 0.6, 
            fontSize: 24, fontFace: "Helvetica Neue", 
            color: "FFFFFF", bold: true, valign: "middle"
        });

        // Content Bullets
        // We use a cleaner layout with spacing
        if (slide.content && slide.content.length > 0) {
            // Background box for content to make it pop
            s.addShape(pres.ShapeType.rect, {
                x: 0.5, y: 1.5, w: 8.8, h: 5.0,
                fill: { color: "F8FAFC" },
                line: { color: "E2E8F0", width: 0.5 }
            });

            s.addText(slide.content.map(c => ({ text: c, options: { breakLine: true } })), {
                x: 0.8, y: 1.8, w: 8.2, h: 4.4,
                fontSize: 18, color: "334155", fontFace: "Arial",
                bullet: { type: "number" }, // FIXED: Removed unsupported 'color' property
                paraSpaceBefore: 12,
                lineSpacing: 28,
                valign: "top"
            });
        }
      }
    });

    await pres.writeFile({ fileName: `${topic.title.replace(/[^a-z0-9]/gi, '_')}.pptx` });
  };

  return (
    <div className="flex flex-col w-full space-y-4">
      <button 
        onClick={slides ? handleDownload : handleGenerate} 
        disabled={isGenerating} 
        className="flex items-center gap-3 px-6 py-4 bg-white dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 rounded-xl hover:border-orange-500 hover:bg-orange-50 dark:hover:bg-orange-900/20 transition-all text-left group shadow-sm w-full"
      >
        <div className="flex-shrink-0 p-3 bg-orange-100 dark:bg-orange-900/50 rounded-full text-orange-600 dark:text-orange-400 group-hover:scale-110 transition-transform">
          {isGenerating ? <RefreshCw className="w-6 h-6 animate-spin" /> : slides ? <FileDown className="w-6 h-6" /> : <Presentation className="w-6 h-6" />}
        </div>
        <div className="flex-1">
          <h4 className="font-bold text-slate-800 dark:text-slate-200 text-lg">
            {slides ? "Download PowerPoint Deck" : "Generate Presentation Deck"}
          </h4>
          <p className="text-sm text-slate-500 dark:text-slate-400">
            {slides ? "Ready for download! Professional layout included." : "Create formatted slides with script & notes."}
          </p>
        </div>
      </button>

      {/* Configuration Panel */}
      {!slides && !isGenerating && (
        <div className="bg-slate-50 dark:bg-slate-900/50 p-4 rounded-xl border border-slate-200 dark:border-slate-700 animate-fade-in">
           <div className="flex flex-wrap gap-4 items-end">
              <div className="flex-1 min-w-[150px]">
                 <label className="text-xs font-bold text-slate-500 uppercase mb-1 block">Slide Count</label>
                 <select 
                   value={slideCount} 
                   onChange={(e) => setSlideCount(parseInt(e.target.value))}
                   className="w-full p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-600 text-sm"
                 >
                    <option value={5}>5 Slides (Brief)</option>
                    <option value={8}>8 Slides (Standard)</option>
                    <option value={12}>12 Slides (Detailed)</option>
                 </select>
              </div>
              <div className="flex-1 min-w-[150px]">
                 <label className="text-xs font-bold text-slate-500 uppercase mb-1 block">Style</label>
                 <select 
                   value={tone} 
                   onChange={(e) => setTone(e.target.value)}
                   className="w-full p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-600 text-sm"
                 >
                    <option value="Professional">Professional (Corporate)</option>
                    <option value="Academic">Academic (University)</option>
                    <option value="Creative">Creative (Workshop)</option>
                 </select>
              </div>
           </div>
        </div>
      )}

      {/* Preview Panel */}
      {slides && (
        <div className="w-full bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-xl overflow-hidden animate-slide-down">
           <div className="p-4 border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 flex justify-between items-center">
              <span className="font-bold text-slate-700 dark:text-slate-300 flex items-center gap-2"><CheckCircle className="w-4 h-4 text-emerald-500" /> {slides.length} Slides Ready</span>
              <button onClick={() => setSlides(null)} className="text-xs text-slate-500 underline hover:text-red-500">Reset</button>
           </div>
           <div className="p-4 grid grid-cols-2 md:grid-cols-4 gap-3 max-h-60 overflow-y-auto custom-scrollbar bg-slate-100 dark:bg-black/20">
              {slides.map((s, i) => (
                 <div key={i} className="aspect-video bg-white dark:bg-slate-700 rounded border border-slate-300 dark:border-slate-600 p-2 flex flex-col relative overflow-hidden group hover:border-indigo-500 transition-colors cursor-default">
                    <div className="absolute top-0 left-0 w-1 h-full bg-indigo-500/20"></div>
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">#{i+1}</span>
                    <p className="text-[11px] font-bold text-slate-800 dark:text-slate-200 line-clamp-2 leading-tight">{s.title}</p>
                    <p className="text-[9px] text-slate-500 mt-auto pt-2 border-t border-slate-100 dark:border-slate-600">{s.content.length} bullets</p>
                 </div>
              ))}
           </div>
        </div>
      )}
    </div>
  );
};


